# Generated by Django 4.2.24 on 2025-09-22 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nurses', '0003_remove_nurseprofile_specialization_nurseprofile_age_and_more'),
        ('patients', '0003_patientprofile_age_patientprofile_care_needed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(default='', editable=False, max_length=15, unique=True)),
                ('report_type', models.CharField(choices=[('daily', 'Daily Care Report'), ('incident', 'Incident Report'), ('progress', 'Progress Report'), ('followup', 'Follow-up Report'), ('discharge', 'Discharge/Completion Report')], max_length=20)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('shift', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=20, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('care_provided', models.TextField(blank=True, null=True)),
                ('medication_given', models.TextField(blank=True, null=True)),
                ('vitals_recorded', models.JSONField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='report_attachments/')),
                ('verified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to='nurses.nurseprofile')),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='nurses.nurseprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='patients.patientprofile')),
            ],
        ),
    ]
