# Generated by Django 4.2.24 on 2025-09-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='vitals_recorded',
            field=models.TextField(blank=True, null=True),
        ),
    ]
