# Generated by Django 4.2.24 on 2025-09-22 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nurses', '0003_remove_nurseprofile_specialization_nurseprofile_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0003_patientprofile_age_patientprofile_care_needed_and_more'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(default='', editable=False, max_length=12, unique=True)),
                ('date_of_appointment', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('visit_period', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=20, null=True)),
                ('recurrence', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20)),
                ('purpose', models.CharField(choices=[('checkup', 'Check-up'), ('wound_care', 'Wound Care'), ('medication', 'Medication'), ('therapy', 'Therapy'), ('emergency', 'Emergency'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('rescheduled_datetime', models.DateTimeField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority_level', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('emergency', 'Emergency')], default='normal', max_length=20)),
                ('transportation_required', models.BooleanField(default=False)),
                ('family_notified', models.BooleanField(default=False)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='appointment_attachments/')),
                ('assigned_nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='nurses.nurseprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('linked_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='reports.report')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patientprofile')),
            ],
        ),
    ]
